spring:
  application:
    name: ofx-service-registry
server:
  port: 8761
  max-http-header-size: 64kb
  ssl:
    enabled: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: DEBUG
    org.apache.http: DEBUG
    org.springframework.web: DEBUG
    dev.luisjohann.ofxpermissionchecker: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
    org.keycloak: DEBUG
    org.keycloak.adapters: DEBUG
    org.keycloak.authentication: DEBUG
    org.keycloak.events: DEBUG
    com:
      netflix:
        eureka: debug
        discovery: debug